ELASTIC_SEARCH_DOMAIN = 'es'
ELASTIC_SEARCH_PORT = 9200
ELASTIC_SEARCH_PROTOCOL = 'http'
ELASTIC_SEARCH_URL = f'{ELASTIC_SEARCH_PROTOCOL}://{ELASTIC_SEARCH_DOMAIN}:{ELASTIC_SEARCH_PORT}'

DISCORD_WEBHOOK = 'https://discord.com/api/webhooks/807561101843628052/UTOFZ5zAlU7ydhi1XdxAQUTVtszBANLyaq9wI7y8samIOMKC7amJuQPRK-PwRFY6VIUB'